SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME FROM ANIMAL_INS I
LEFT OUTER JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID=O.ANIMAL_ID
WHERE I.SEX_UPON_INTAKE LIKE 'intact%' 
AND O.SEX_UPON_OUTCOME NOT LIKE 'intact%'
ORDER BY I.ANIMAL_ID 