# DISTINCT : 중복되지 않고 NULL 제외되는 값만 COUNT

### 방법 1
SELECT COUNT(DISTINCT NAME) FROM ANIMAL_INS


### 방법 2 (괄호만 다름)
SELECT COUNT(DISTINCT(NAME)) FROM ANIMAL_INS


### 방법 3
SELECT COUNT(A.NAME) count
FROM (SELECT NAME FROM ANIMAL_INS GROUP BY NAME) AS A
WHERE NAME IS NOT NULL 